/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as AAppTokenRouteImport } from './routes/a.$appToken'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicPurgeStorageRouteImport } from './routes/api/public/purge-storage'
import { Route as ApiPublicMailersendRouteImport } from './routes/api/public/mailersend'
import { Route as AuthenticatedProgramsIdRouteImport } from './routes/_authenticated/programs.$id'
import { Route as AuthenticatedApplicationsIdRouteImport } from './routes/_authenticated/applications.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AAppTokenRoute = AAppTokenRouteImport.update({
  id: '/a/$appToken',
  path: '/a/$appToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPurgeStorageRoute = ApiPublicPurgeStorageRouteImport.update({
  id: '/api/public/purge-storage',
  path: '/api/public/purge-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMailersendRoute = ApiPublicMailersendRouteImport.update({
  id: '/api/public/mailersend',
  path: '/api/public/mailersend',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgramsIdRoute = AuthenticatedProgramsIdRouteImport.update({
  id: '/programs/$id',
  path: '/programs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsIdRoute =
  AuthenticatedApplicationsIdRouteImport.update({
    id: '/applications/$id',
    path: '/applications/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/a/$appToken': typeof AAppTokenRoute
  '/r/$token': typeof RTokenRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/programs/$id': typeof AuthenticatedProgramsIdRoute
  '/api/public/mailersend': typeof ApiPublicMailersendRoute
  '/api/public/purge-storage': typeof ApiPublicPurgeStorageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/a/$appToken': typeof AAppTokenRoute
  '/r/$token': typeof RTokenRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/programs/$id': typeof AuthenticatedProgramsIdRoute
  '/api/public/mailersend': typeof ApiPublicMailersendRoute
  '/api/public/purge-storage': typeof ApiPublicPurgeStorageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/a/$appToken': typeof AAppTokenRoute
  '/r/$token': typeof RTokenRoute
  '/_authenticated/applications/$id': typeof AuthenticatedApplicationsIdRoute
  '/_authenticated/programs/$id': typeof AuthenticatedProgramsIdRoute
  '/api/public/mailersend': typeof ApiPublicMailersendRoute
  '/api/public/purge-storage': typeof ApiPublicPurgeStorageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/a/$appToken'
    | '/r/$token'
    | '/applications/$id'
    | '/programs/$id'
    | '/api/public/mailersend'
    | '/api/public/purge-storage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/a/$appToken'
    | '/r/$token'
    | '/applications/$id'
    | '/programs/$id'
    | '/api/public/mailersend'
    | '/api/public/purge-storage'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/a/$appToken'
    | '/r/$token'
    | '/_authenticated/applications/$id'
    | '/_authenticated/programs/$id'
    | '/api/public/mailersend'
    | '/api/public/purge-storage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AAppTokenRoute: typeof AAppTokenRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicMailersendRoute: typeof ApiPublicMailersendRoute
  ApiPublicPurgeStorageRoute: typeof ApiPublicPurgeStorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$appToken': {
      id: '/a/$appToken'
      path: '/a/$appToken'
      fullPath: '/a/$appToken'
      preLoaderRoute: typeof AAppTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/purge-storage': {
      id: '/api/public/purge-storage'
      path: '/api/public/purge-storage'
      fullPath: '/api/public/purge-storage'
      preLoaderRoute: typeof ApiPublicPurgeStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mailersend': {
      id: '/api/public/mailersend'
      path: '/api/public/mailersend'
      fullPath: '/api/public/mailersend'
      preLoaderRoute: typeof ApiPublicMailersendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/programs/$id': {
      id: '/_authenticated/programs/$id'
      path: '/programs/$id'
      fullPath: '/programs/$id'
      preLoaderRoute: typeof AuthenticatedProgramsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/$id': {
      id: '/_authenticated/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AuthenticatedApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedApplicationsIdRoute: typeof AuthenticatedApplicationsIdRoute
  AuthenticatedProgramsIdRoute: typeof AuthenticatedProgramsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedApplicationsIdRoute: AuthenticatedApplicationsIdRoute,
  AuthenticatedProgramsIdRoute: AuthenticatedProgramsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AAppTokenRoute: AAppTokenRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicMailersendRoute: ApiPublicMailersendRoute,
  ApiPublicPurgeStorageRoute: ApiPublicPurgeStorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
